- dibi/drivers/DibiOracleDriver.php
This is useful when your application needs to work with a different oracle schema than its default one.
> Oracle: adds support for login schema option

- dibi/drivers/DibiPdoDriver.php
Fixed escaping for linux version of mssql driver - dblib.
> DibiPdoDriver::escape() added support for dblib

- src/Dibi/Drivers/PdoDriver.php
PDO instance is disconnected when there is no other reference to the instance remaining. However when PDO instance is passed to the driver using `$config['pdo']` or `$config['resource']`, it remains in the config array. And then, the disconnect() does not work as intended.
NOT freeing the PDO instance from config prevents the disconnection using the `disconnect()` method.
> Allow disconnecting when passing PDO instance.

- src/Dibi/Drivers/SqlsrvDriver.php
- src/Dibi/Drivers/SqlsrvReflector.php
- tests/databases.appveyor.ini
- tests/dibi/Connection.fetch.phpt
- tests/dibi/Fluent.fetch.limit.mssql.phpt
- tests/dibi/Fluent.fetch.phpt
- tests/dibi/Fluent.select.phpt
- tests/dibi/Result.meta.phpt
- tests/dibi/Sqlsrv.limits.phpt
- tests/dibi/Translator.phpt
- tests/dibi/data/sqlsrv.sql
- tests/dibi/meta.phpt
fixed limit & offset
fixed index and table metadata loading
fixed tests for sqlsrv
changed AppVeyor SQL Server environment from 2008 to 2012 (version 2008 remains incompatible)
NOTE: meta.phpt(20) will fail, because on AppVeyor database, there is schema dbo with 9 tables instead of 3:
```
spt_fallback_db [BASE TABLE]
spt_fallback_dev [BASE TABLE]
spt_fallback_usg [BASE TABLE]
products [BASE TABLE]
customers [BASE TABLE]
orders [BASE TABLE]
MSreplication_options [BASE TABLE]
spt_values [VIEW]
spt_monitor [BASE TABLE]
```
> SqlsrvDriver compatibility fix for SQL Server 2012 and 2014

- src/Dibi/Drivers/SqlsrvDriver.php
When connection to sql server (version 2012) using 
```yaml
db:
host: 'url\instance'
driver: sqlsrv
database: dbname
username: username
password: 123456
```
then sql server wont respond, because password is an integer and not a string. This PR fixes this type conversion.
> SqlsrvDriver: fixed: sql server does not respond on non-string password

- src/Dibi/Drivers/MySqlDriver.php
- src/Dibi/Drivers/MySqliDriver.php
- src/Dibi/Drivers/PostgreDriver.php
- tests/dibi/Connection.connect.phpt
Sometimes database go away and Connection::isConnected() is returning TRUE. Prevent this should be posibble to disconnect on closed connection without error.
> Disconnect on not connected driver not fail

- src/Dibi/Drivers/PostgreDriver.php
Allows set more than one schema to current search_path, by an array of schema names in `$config['schema']` connection parameter.
`SET search_path TO "myschema", "public";`
> PostgreSQL: add support for more than one schema in search_path

- src/Dibi/Drivers/OracleDriver.php
In current state formatting date (%d) or datetimes (%t) in query reproducing malformed sql
**This example:**
``` php
$dibi->select('*')
->from('SAMPLE_TABLE')
->where('COLUMN_DT = %d', new \DateTime('2016-08-05 12:00:00'));
```
**Will generate this sql:**
``` sql
SELECT * FROM "SAMPLE_TABLE" WHERE COLUMN_DT = 1470391200
```
**which produce error:**
<code>
ORA-00932: inconsistent datatypes: expected DATE got NUMBER
</code>
In oracle, value should be converted into date by to_date() function. Second parameter for this function is optional mask, if its not provided then oracle try guess format by NLS parameters. This patch solving problem in secure way.
[See oracle documentation](http://www.techonthenet.com/oracle/functions/to_date.php)
Result for same fluent as before will be this:
``` sql …
```
> OracleDriver: Fixed dates escaping

- src/Dibi/Result.php
- tests/dibi/Connection.fetch.phpt
- bug fix? yes
- BC break? no
`Result::fetch()` can return `array` for `setRowClass(null)`.
> Result: strict type fix

- src/Dibi/Bridges/Tracy/Panel.php
- bug fix? yes
- BC break? no
Fixing:
```
Error in panel Dibi\Bridges\Tracy\Panel::renderException
TypeError: Return value of Dibi\Bridges\Tracy\Panel::renderException() must be of the type array or null, none returned in ...\vendor\dibi\dibi\src\Dibi\Bridges\Tracy\Panel.php:78
```
> Tracy\Panel: fixed TypeError in renderException()

- src/Dibi/Drivers/MySqliDriver.php
- src/Dibi/Drivers/OracleDriver.php
- src/Dibi/Drivers/PostgreDriver.php
- src/Dibi/Drivers/Sqlite3Driver.php
- bug fix? no
- BC break? no
I would like to override public static method `createException()` and add more exception types for PostgreSQL.
> Make drivers more extensible

- src/Dibi/Drivers/PostgreDriver.php
- bug fix? yes. Issue #270 
- BC break? no
Postgres can return a string when selecting 'LASTVAL' or 'CURRVAL'. This code change ensures that an integer is always returned when calling 'Dibi\Drivers\PostgreDriver::getInsertId'
> Ensuring that an integer is returned, if postgres returned a string within Dibi\Drivers\PostgreDriver::getInsertId

- src/Dibi/Drivers/FirebirdDriver.php
- bug fix? yes - fixes #273
- BC break? no
The Firebird driver formats full date & time with microsecond precision, but this results in a conversion error when run against a Firebird 3.0.1 server. TIMESTAMP in Firebird Dialect 3 (which itself is equivalent to DATE in Dialect 1) only supports decimillisecond resolution (10e-4).
> fix Firebird datetime precision

- src/Dibi/exceptions.php
- bug fix? no
- BC break? no
Fixes #254 (hope I didn't forget anything).
Note: I didn't add the `$previous` argument to `ProcedureException` constructor because it seemed to be an internal exception and its usage didn't suggest it could benefit from such argument.
> Previous exception can now be passed to Dibi\Exception constructor

- src/Dibi/Connection.php
- src/Dibi/interfaces.php
- bug fix? no   related to https://github.com/dg/dibi/issues/244
- new feature? yes (partially)
- BC break? no
Why it's useful:
Let's say I have a great SQL builder in my codebase which internally use Dibi\Connection to communicate with database.
When I'm trying to make a unit test of that code, I can write something like this:
```
class AwesomeBuilderTestCase extends TestCase
{
public function testBasicFunctionality()
{
$connection = Mockery::mock(Connection::class)
->shouldReceive('query')->once()->withArgs(['SELECT foo FROM bar'])->getMock();
$builder = new MyAwesomeSqlBuilder($connection);
$builder->build(['foo', 'bar']);
\Mockery::close();
}
}
```
but unfortunately now it cannot be done, because query method is marked as final. But if I will use interface instead, it can be done. …
> add interface for connection

- src/Dibi/Connection.php
- src/Dibi/Drivers/FirebirdDriver.php
- src/Dibi/Drivers/MsSqlDriver.php
- src/Dibi/Drivers/MySqliDriver.php
- src/Dibi/Drivers/OdbcDriver.php
- src/Dibi/Drivers/OracleDriver.php
- src/Dibi/Drivers/PdoDriver.php
- src/Dibi/Drivers/PostgreDriver.php
- src/Dibi/Drivers/Sqlite3Driver.php
- src/Dibi/Drivers/SqlsrvDriver.php
- src/Dibi/interfaces.php
- BC break? yes
Instance of driver exists as long as exist DB connection (instead of object Dibi\Connection). So driver's property `$resource` is always `resource` or `mysqli` object, and not `resource|null` or `mysqli|null`.
cc @milo
> driver's connect() & disconnect() replaced with constructor & desctructor

- src/Dibi/Fluent.php
has been introduced by this commit:
https://github.com/dg/dibi/commit/0d5fd9d65b6421d871834dbc5026835b06da7313
for example fluent:
```
$dibiConnection->select(‘id’)
->from(‘users’);
```
will not pass static analysis although is completely valid code.
- bug fix
- BC break? no
Anyway thanks for a great tool for simple stuff with SQL - saved a lot of work already 🙏 .
> this extra type will break a static analysis for usage without alias

- src/Dibi/Reflection/Column.php
- bug fix
- BC break? no
fix for:
TypeError: Return value of Dibi\Reflection\Column::getType() must be of the type string, null returned
> fix Type Error

- src/Dibi/Drivers/PostgreReflector.php
- bug fix
- BC break? no
fix for TypeError: substr() expects parameter 1 to be string, null given
> fix TypeError: substr() expects parameter 1 to be string, null given

- src/Dibi/Connection.php
- src/Dibi/Drivers/FirebirdDriver.php
- tests/dibi/Connection.connect.phpt
- new feature
- BC break? no
onConnect option is an array of SQL queries run by `Connection::query()` right after a database connection is established.
It is "hard" to run SQL queries once when a connection is established, especially in non-lazy configuration. Such queries are usually part of the connection setup phase, like:
- `['ALTER SESSION SET NLS_DATE_FORMAT = %s', 'YYYY-MM-DD']` (by Oracle)
- `PRAGMA foreign_keys=true` by #301 (by SQLite)
- `SET application_name = 'MyApp';` (by PostgreSQL)
In lazy mode, the `Dibi\Event` can be used, but such event is invoked by every next SQL query which is not necessary. Moreover, when used with Nette DI, it requires some stuff/boilerplate code to achive that. This solution seems clear to me, setup queries are kept near configuration.
For …
> Connection config onConnect

- src/Dibi/Drivers/PdoDriver.php
- tests/dibi/PdoDriver.providedConnection.phpt
- bug fix
- BC break? no (as original behaviour should be considered as broken)
see #292
> PdoDriver: check for misconfigured PDO connections resource (target 3.3.x and 4.0.x)

- src/Dibi/Result.php
- tests/dibi/Result.normalize.phpt
* bug fix #317 for version master
* BC break? no
* changes as suggested in #317
> Result::normalize() Fix select float in format of e-notation (#317) master

- src/Dibi/Result.php
- tests/dibi/Result.normalize.phpt
* bug fix #317 for version v3.2
* BC break? no
* changes as suggested in #317
> Result::normalize() Fix select float in format of e-notation (#317) v3.2

- src/Dibi/Result.php
- bug fix / new feature?
new feature
- BC break? yes/no
no
Added getTypes method, to get all columns and its types, this is faster then write foreach for getting all columns, and getColumns do not get column type (there is null).
> Add Result::getTypes to get all columns and its types

- src/Dibi/Fluent.php
- new feature
- BC break? no
Allows static analyst tools to understand code like :
`$fluent->where('columnA = 1')->or('columnB = 2');`
> Dibi\Fluent: add annotation for methods or()

- src/Dibi/Drivers/SqlsrvDriver.php
- src/Dibi/Drivers/SqlsrvReflector.php
- tests/dibi/Fluent.select.phpt
- tests/dibi/Translator.conditions.phpt
- tests/dibi/Translator.phpt
In case nvarchar type is used and e.g. chinese have to be saved, there have to be N in front of the value, this escaping works fine for varchar columns as well.
- bug fix
> SqlsrvDriver: Correct escaping of special characters (N prefix)

- tests/dibi/Translator.DateInterval.phpt
Dibi returns `TIME` values as `DateInterval` (for MySQL) but using of `DateInterval` in queries fails with `**Unexpected DateInterval**`.
See https://forum.nette.org/cs/32482-dibi-sloupec-time-a-jeho-zapis#p205778
I don't know how to fix it - maybe add new `Driver::escapeTime()` method?
> Failing test for DateInterval usage

- src/Dibi/Connection.php
- src/Dibi/Result.php
- BC break? no
`Dibi\Connection($config)` -> added new option `$config['result']['formatJson']` to tell the `Dibi\Result` how to format `json` column. 3 options available: `array` (default, therefore no BC breaks), `object` (formatting json to \stdClass) and `string`.
> Connection: added option [result][formatJson] that sets json column decoding (string|object|array)

- src/Dibi/Drivers/SqlsrvResult.php
On error, sqlsrv_fetch_array() returns false, which causes an error due to the return type declaration. This commit handles that by casting such value to null the same way other result drivers do it.
> SqlsrvResult: fixed illegal false return value from sqlsrv_fetch_array()

- readme.md
- src/Dibi/Drivers/FirebirdDriver.php
- src/Dibi/Drivers/MySqliDriver.php
- src/Dibi/Drivers/OdbcDriver.php
- src/Dibi/Drivers/OracleDriver.php
- src/Dibi/Drivers/PdoDriver.php
- src/Dibi/Drivers/PostgreDriver.php
- src/Dibi/Drivers/SqliteDriver.php
- src/Dibi/Drivers/SqlsrvDriver.php
- src/Dibi/Translator.php
- src/Dibi/interfaces.php
- tests/dibi/Translator.like.phpt
It is required if you need to ignore letter case or diacritics on certain collations while maintaining characters properly escaped in LIKE query.
Tests added, not tested though.
> Add support for escapeLike without % on any side

- src/Dibi/Drivers/PostgreDriver.php
- bug fix: config parameter 'persistent' has no effect on the connection
> PostgreDriver: fixed persistent connections

- examples/using-logger.php
- src/Dibi/Connection.php
- src/Dibi/Loggers/FileLogger.php
- new feature  #350 Add option to log errors only
- BC break? no
This PR adds a new option on the profiler config to allow the logging of errors and other small changes in the ```FileLogger``` to reduce duplicated code.
> FileLogger: Add option to log errors only

- tests/dibi/Connection.connect.phpt
- bug fix: yes
- BC break? no
Escaping of string escape functions should works on reconnected connection.
> tests: added reconnect test

- src/Dibi/Drivers/MySqliDriver.php
mysqli::real_connect() expects parameter 3 to be string, yields an error on NULL.
- bug fix
- not a BC break
> MySqliDriver: coalesced password to an empty string

- composer.json
- src/Dibi/Bridges/Tracy/Panel.php
- src/Dibi/Connection.php
- src/Dibi/Drivers/FirebirdDriver.php
- src/Dibi/Drivers/FirebirdResult.php
- src/Dibi/Drivers/MySqliDriver.php
- src/Dibi/Drivers/MySqliResult.php
- src/Dibi/Drivers/OdbcDriver.php
- src/Dibi/Drivers/OracleDriver.php
- src/Dibi/Drivers/OracleResult.php
- src/Dibi/Fluent.php
- src/Dibi/Helpers.php
- src/Dibi/Result.php
- src/Dibi/Translator.php
- new feature
- BC break? yes
I fixed some PhpStan errors.
> PhpStan fixes

- src/Dibi/Bridges/Tracy/Panel.php
- bug fix
- BC break? no
With a custom driver, Tracy panel failed to render with message `Object ... could not be converted to string`
> Tracy\Panel: fixed object to string converion error with custom driver

- src/Dibi/Loggers/FileLogger.php
- bug fix
- BC break? no
Same as #373 and I hope I already found all places.
> FileLogger: fixed object to string conversion with custom driver

- src/Dibi/Drivers/MySqliDriver.php
- new feature, see #144 
- BC break? no
See [PHP `mysqli::ping()` manual](https://www.php.net/manual/en/mysqli.ping.php), relevant to #144, but MySQL driver.
> MySqliDriver: added support for ping

- src/Dibi/Drivers/PostgreDriver.php
- adds the option to pass the connect_type as config parameter
- PHP default is 0, but to make this change non-breaking defauls to PGSQL_CONNECT_FORCE_NEW
- see PHP docs: https://www.php.net/manual/en/function.pg-connect.php
- new approach to issue #353
- BC break? no
> Postgre driver - add connect_type config parameter

- src/Dibi/Helpers.php
- bug fix - yes
- BC break? no
Dibi/Helpers::getSuggestion(): item may be an int, type cast fix, query example:
SELECT 1 FROM `users`
> Dibi/Helpers::getSuggestion(): item may be an int, type cast fix

- src/Dibi/Drivers/PostgreReflector.php
- bug fix #380 
- BC break? no
As comparing string and number has changed and PostgreSQL version 7.4 is outdated (~year 2003), I have removed the check altogether. @dg are you OK with that?
> PostgreReflector: removed version check

- src/Dibi/Drivers/PostgreDriver.php
- bug fix
- BC break? no
Sometimes I use something like `self::class . __LINE__` as save point name. It is supported by PostgreSQL, however Dibi has been missing support for escaping such named identifier. This PR fixes the problem.
> PostgreSQL driver: fixed handling of complex save point name

- src/Dibi/Connection.php
- src/Dibi/Event.php
- src/Dibi/dibi.php
- tests/dibi/Connection.transactions.phpt
- tests/dibi/Result.meta.phpt
- bug fixes & new feature
- BC break? no
First commits are some fixes, but main purpose of this PR is to allow nested `Connection::transaction()` calls. For example, this is useful if you have dependent repositories and in one you call:
```php
public function savePerson($data)
{
$this->db->transaction(function () {...});
}
```
and in other one
```php
public function save()
{
$this->db->transaction(function ($db) {
$this->repo1->savePerson(...);
$this->repo2->saveMoney(...);
$this->repo3->saveAddresses(...);
$db->query('UPDATE ....');
});
}
```
I'm already using this concept more than 5 years and never hit any problem.
One note to implementation: nesting can be implemented in the `begin()`, `commit()` and `rollback()` methods but it brings some questions in an user code. Imagine this: …
> Nested trasactions

- src/Dibi/Helpers.php
- bug fix
- BC break? probably not
Dibi is currently unable to handle [PostgreSQL range types](https://www.postgresql.org/docs/current/rangetypes.html), as it attempts to convert their values into single-value data types such as a float/int or a DateTime. This is logically not possible and results in TypeError or Exception, depending on the type:
`DateTime::__construct(): Failed to parse time string ((,)) at position 0 ((): Unexpected character`
For example int4range contains values such as `[2,3)` or `empty`, so it is also impossible to convert into a single numeric type.
I think a reasonable solution is to use the same approach as with PostgreSQL arrays and simply treat all range types as `Type::TEXT`. This will keep the raw range value intact and avoid typecasting errors.
Although this …
> Helpers::detectType(): detect PostgreSQL range types as Type::TEXT

- src/Dibi/Translator.php
- tests/dibi/Translator.enums.phpt
- new feature
- BC break? no
Backed enumerations are translated to their scalar values.
> Translator: convert BackedEnum to scalar

- src/Dibi/Drivers/MySqliDriver.php
- tests/databases.appveyor.ini
- tests/databases.github.ini
- tests/dibi/Driver.mysqli.phpt
> MySqliDriver::getResource() fixed usage of resource being closed prior to the call in PHP 8

- src/Dibi/Connection.php
- bug fix
Change typehint for ```$onEvent``` from ```array``` to ```?array```
due:
https://github.com/dg/dibi/blob/master/src/Dibi/Bridges/Tracy/Panel.php#L122
thanks
> Connection: fixed typehint

- src/Dibi/Bridges/Tracy/Panel.php
- bug fix
- BC break? no
Non-breakable space entity in Tracy panel markup was converted to `\u{a0}` escape sequence, however it was kept inside of single quoted string, which prevents it from being recognized as an escape sequence and results in text `\u{a0}` being output into the Dibi Tracy panel heading.
Affected versions: only 4.2.6
> Panel: move escape sequence to double-quoted string

- src/Dibi/Event.php
- tests/dibi/Event.source.phpt
Got rid of filesystem (OS stat) checks per each event.
https://github.com/dg/dibi/issues/426
> Detecting event source without filesystem checks

- appveyor.yml
- src/Dibi/Connection.php
- src/Dibi/Translator.php
- tests/databases.appveyor.ini
- tests/databases.sample.ini
- tests/dibi/Connection.objectTranslator.phpt
- tests/dibi/data/mysql.sql
- tests/dibi/meta.phpt
- tests/dibi/mysql.time.phpt
Another approach of #429
API is:
```php
Connection::setObjectTranslator(string $class, callable $translator): void
$connection->setObjectTranslator(Email::class, fn($email) => new Expression('?', $email->address));
```
If you consider it useful, last commit changes API and the target class is detected from `$translator` parameter typehint:
```php
Connection::setObjectTranslator(callable $translator): void
$connection->setObjectTranslator(fn(Email $email) => new Expression('?', $email->address));
```
> Object translator No.2

- readme.md
fixes transaction method name
- bug fix
- BC break? no
There's no `beginTransaction` method.
```plain
LogicException: Call to undefined method Dibi\Connection::beginTransaction()
```
> Update readme.md, fixes `transaction` method name

- src/Dibi/Drivers/SqliteResult.php
Bug fix; bc break: NO.
Same as #430 for v4.2
> SqLite: Fix fatal error when resource closed prior to result destructing

- src/Dibi/Fluent.php
Conditional return type makes PHPStan understand whether execute() returns int or Result
> Fluent: execute() has conditional return type

- src/Dibi/Row.php
- BC break? no
Same as #443 for the v4.x branch.
> Add mixed type hint for magic properties (v4.x)

- src/Dibi/Drivers/PostgreReflector.php
- bug fix
- BC break? probably not
- versions affected: all
When an autoincrement column is not in the first position of primary key index, PostgreReflector is unable to detect it. This seems like a rather arbitrary check, which is also inconsistent with other drivers such as MySqlReflector; MySqlReflector doesn't require autoincrement columns to be part of a primary key at all to detect them.
My commit removes the primary key check from PostgreReflector autoincrement detection entirely, making it consistent with MySqlReflector and allowing PostgreReflector to detect autoincrement columns anywhere in the table.
This is potentially a BC break for someone who relies on PostgreReflector's failure to detect autoincrement columns outside the first position of primary key index.
Additionally, …
> PostgreReflector: fix autoincrement column detection

- src/Dibi/Bridges/Nette/DibiExtension3.php
- bug fix
- BC break? no
v5.0.1
In Dibi\Connection.php: Helpers::alias($config, 'result|formatDate', 'resultDate');
Only with DibiExtension3. With DibiExtension22 it is ok.
> Fixed "Cannot use object of type stdClass as array"

- src/Dibi/Result.php
- tests/dibi/Result.normalize.phpt
- bug fix
- BC break? no
I updated [Result::normalize()](https://github.com/typekcz/dibi/blob/7c9ff39822ba692468cbc79f70f6385dc981bb8b/src/Dibi/Result.php#L468) so that it can handle float normalization of negative numbers better.
More specifically numbers between -1 and 0 are returned from Oracle driver without 0 before decimal separator. For example `-.1` can be returned by Oracle, but fails in Result::normalize().
I added test cases for negative floats which all passed.
> Result::normalize() Fixed normalization of "-." numbers

- .github/workflows/coding-style.yml
- .github/workflows/static-analysis.yml
- .github/workflows/tests.yml
- src/Dibi/Translator.php
- bug fix
- BC break? no
We have some numeric columns in database for which Dibi fails with TypeError `explode() expects parameter 2 to be string, int given`.
I have fixed the case `a` that failed in our code, but it seems the same issue might be in cases `v` and `m` as well. I don't quite understand Dibi internals so I am unable to verify if it's a real problem in these cases.
The issue happens with code like `$connection->update('table', [10 => 'foo'])>where('id = %i', 1)->execute();`
If you could also backport the fix to the v4.2 branch, it would be welcome.
Thank you
> Fix numeric column formatting

- src/Dibi/Bridges/Nette/DibiExtension3.php
- bug fix
- BC break? no
[This fix](https://github.com/dg/dibi/commit/7c9ff39822ba692468cbc79f70f6385dc981bb8b) tried to fix the schema so that `$config['result']` is an array and not `stdClass`.
However, `Expect::array()` doesn't process the fields recursively, it just checks that the type is array and uses the argument as a default value. That leads to `Argument #2 ($normalize) must be of type bool, Nette\Schema\Elements\Type given`.
The correct way is to use `Expect::structure()` and then cast it to array (instead of `stdClass`).
> DibiExtension3: fixed schema, process 'result' recursively
